version: '3.7'

services:
  farmfarm-server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 80:3333
    env_file:
      - ./.env.docker

  farmfarm-db:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: 'farmfarm'
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
    ports:
      - 3306:3306
